### ISSUE TITLE
Cannot execute request.

### ISSUE THREAD

**Issue by tst-038** [xerbalind/dodona.nvim#4]
I have added my token and do not get any visible errors
Yet when I try do run dodonasubmit I get the following errors
- Cannot execute request.
- Unauthorized request: make sure you have working token.
- submit failed

when I try running dodonaInitActivities telescope opens but is completely empty.

are there any specific things that should be done?

**Comment by xerbalind** [comment]
It's been a while since I've maintained this plugin, seems some things have changed with the dodona API... Fixing it now.

**Comment by xerbalind** [comment]
The main issue was that the base url should now be `https://dodona.be` in the config file. I have also fixed some small issues and  updated the README. This should resolve the described problems.

**Comment by tst-038** [comment]
It worked great for python however as soon as I tried bash I get errors initiating the activities.
`E5108: Error executing lua: ...local/share/nvim/lazy/dodona.nvim/lua/dodona/manager.lua:42: attempt to concatenate a nil value
stack traceback:
        ...local/share/nvim/lazy/dodona.nvim/lua/dodona/manager.lua:42: in function 'createFiles'
        ...cal/share/nvim/lazy/dodona.nvim/lua/dodona/telescope.lua:20: in function 'run_replace_or_original'
        ...re/nvim/lazy/telescope.nvim/lua/telescope/actions/mt.lua:65: in function 'key_func'
        ...hare/nvim/lazy/telescope.nvim/lua/telescope/mappings.lua:253: in function <...hare/nvim/lazy/telescope.nvim/lua/telescope/mappin
gs.lua:252>`
I just tested java and that worked fine to...

Also dodonago still does not work (extra dependency? no errors just nothing happens)

submit works like it should!

**Comment by xerbalind** [comment]
The error you get should be fixed, its the result for some functionality I added yesterday whoops :sweat_smile:.

As for `DodonaGo`, it previously opened `firefox`, I've made it now more generic and have added an optional config parameter that allows you to set the command it should execute (See the updated README).

Its possible the default option now works on your machine.

**Comment by tst-038** [comment]
It is indeed fixed!
I use safari instead of firefox so that's probably why it still doesn't work.

DodonaGo is nice but not to important to me
I absolutely love the initActivities tho!
Thanks for the quick support!

**Comment by xerbalind** [comment]
adding `go_cmd = "open"` in config should make `DodonaGo` work (if you use macOS).

**Comment by tst-038** [comment]
oh yeah that does indeed work!
